export const moviesData = [
  {
    phase: "I",
    title: "IRON MAN",
    date: "29 JANUARY 2008",
    img: "../../public/img/ironman.jpg",
    heroes: ["IRON MAN", "IRON MONGER", "NICK FURY"],
  },
  {
    phase: "I",
    title: "THE INCREDIBLE HULK",
    date: "13 JUNE 2008",
    img: "",
    heroes: ["HULK", "ABOMINATION", "GENERAL ROSS"],
  },
  {
    phase: "I",
    title: "IRON MAN 2",
    date: "30 APRIL 2010",
    img: "",
    heroes: [
      "IRON MAN",
      "WAR MACHINE",
      "BLACK WIDOW",
      "JUSTIN HAMMER",
      "WHIPLASH",
      "NICK FURY",
      "PHIL COULSON",
    ],
  },
  {
    phase: "I",
    title: "CAPITAN AMERICA: THE FIRST AVENGER",
    date: "5 AUGUST 2011",
    img: "",
    heroes: ["CAPITAN AMERICA", "RED SKULL", "PEGGY CARTER", "BUCKY BARNES"],
  },
  {
    phase: "I",
    title: "THOR",
    date: "29 APRIL 2011",
    img: "",
    heroes: [
      "LOKI",
      "THOR",
      "ODYN",
      "HEIMDAL",
      "JANE FOSTER",
      "PHIL COULSON",
      "HAWKEYE",
      "NICK FURY",
      "DARCY LEWIS",
    ],
  },
  {
    phase: "I",
    title: "THE AVENGERS",
    date: "11 MAY 2012",
    img: "",
    heroes: [
      "IRON MAN",
      "CAPITAN AMERICA",
      "HULK",
      "THOR",
      "BLACK WIDOW",
      "HAWKEYE",
      "LOKI",
      "PHIL COULSON",
      "MARIA HILL",
    ],
  },
  {
    phase: "II",
    title: "IRON MAN 3",
    date: "9 MAY 2013",
    img: "",
    heroes: ["IRON MAN", "WAR MACHINE", "MANDARYN", "BUCKY BARNES"],
  },
  {
    phase: "II",
    title: "THOR: THE DARK WORLD",
    date: "8 OCTOBER 2013",
    img: "",
    heroes: [
      "THOR",
      "LOKI",
      "JANE FOSTER",
      "ODYN",
      "MALEKITH",
      "HEIMDAL",
      "DARCY LEWIS",
    ],
  },
  {
    phase: "II",
    title: "GUARDIANS OF THE GALAXY",
    date: "1 AUGUST 2014",
    img: "",
    heroes: [
      "STAR-LORD",
      "GAMORA",
      "DRAX",
      "GROOT",
      "ROCKET",
      "RONAN",
      "YONDU",
      "NEBULA",
      "THANOS",
    ],
  },
  {
    phase: "II",
    title: "CAPITAN AMERICA: THE WINTER SOLDIER",
    date: "26 MARCH 2014",
    img: "",
    heroes: [
      "CAPITAN AMERICA",
      "WINTER SOLDIER",
      "BLACK WIDOW",
      "NICK FURY",
      "FALCON",
      "MARIA HILL",
      "SHARON CARTER",
    ],
  },

  {
    phase: "II",
    title: "AVENGERS: AGE OF ULTRON",
    date: "7 MAY 2015",
    img: "",
    heroes: [
      "IRON MAN",
      "THOR",
      "HULK",
      "CAPITAN AMERICA",
      "BLACK WIDOW",
      "HAWKEYE",
      "ULTRON",
      "NICK FURY",
      "WAR MACHINE",
      "QUICKSILVER",
      "SCARLET WITCH",
      "VISION",
      "KLAW",
      "MARIA HILL",
      "FALCON",
      "HEIMDAL",
      "LOKI",
      "THANOS",
    ],
  },

  {
    phase: "II",
    title: "ANT-MAN",
    date: "17 JULY 2015",
    img: "",
    heroes: [
      "ANT-MAN",
      "HANK PYM",
      "YELLOWJACKET",
      "CASSANDRA LANG",
      "FALCON",
      "WASP",
    ],
  },

  {
    phase: "III",
    title: "CAPITAN AMERICA: CIVIL WAR",
    date: "6 MAY 2016",
    img: "",
    heroes: [
      "IRON MAN",
      "CAPITAN AMERICA",
      "BLACK WIDOW",
      "WINTER SOLDIER",
      "FALCON",
      "WAR MACHINE",
      "HAWKEYE",
      "BLACK PANTHER",
      "VISION",
      "SCARLET WITCH",
      "ANT-MAN",
      "SHARON CARTER",
      "SPIDER-MAN",
      "ZEMO",
    ],
  },

  {
    phase: "III",
    title: "DOCTOR STRANGE",
    date: "26 OCTOBER 2016",
    img: "",
    heroes: [
      "DOCTOR STRANGE",
      "BARON MORDO",
      "WONG",
      "KAECILIUS",
      "DORMAMMU",
      "ANCIENT ONE",
      "THOR",
      "DR. CHRISTINE PALMER",
    ],
  },

  {
    phase: "III",
    title: "GUARDIANS OF THE GALAXY: vol. 2",
    date: "5 MAY 2017",
    img: "",
    heroes: [
      "STAR-LORD",
      "GAMORA",
      "DRAX",
      "GROOT",
      "ROCKET",
      "EGO",
      "YONDU",
      "NEBULA",
      "MANTIS",
      "THE GRAND MASTER",
    ],
  },

  {
    phase: "III",
    title: "SPIDER-MAN: HOMECOMING",
    date: "14 JULY 2017",
    img: "",
    heroes: ["SPIDER-MAN", "VULTURE", "IRON MAN"],
  },
  {
    phase: "III",
    title: "THOR: RAGNAROK",
    date: "25 OCTOBER 2017",
    img: "",
    heroes: [
      "THOR",
      "LOKI",
      "HELA",
      "HEIMDAL",
      "THE GRAND MASTER",
      "VALKYRIE",
      "HULK",
      "ODYN",
      "DOCTOR STRANGE",
      "KORG",
    ],
  },

  {
    phase: "III",
    title: "BLACK PANTHER",
    date: "5 MAY 2017",
    img: "",
    heroes: [
      "BLACK PANTHER",
      "KLAW",
      "KILLMONGER",
      "NAKIA",
      "OKOYE",
      "SHURI",
      "MAN-APE",
    ],
  },

  {
    phase: "III",
    title: "AVENGERS: INFINITY WAR",
    date: "26 APRIL 2018",
    img: "",
    heroes: [
      "IRON MAN",
      "THOR",
      "HULK",
      "CAPITAN AMERICA",
      "BLACK PANTHER",
      "BLACK WIDOW",
      "DOCTOR STRANGE",
      "THANOS",
      "WAR MACHINE",
      "SPIDER-MAN",
      "GAMORA",
      "NEBULA",
      "LOKI",
      "VISION",
      "SCARLET WITCH",
      "FALCON",
      "WINTER SOLDIER",
      "HEIMDAL",
      "OKOYE",
      "WONG",
      "MANTIS",
      "DRAX",
      "GROOT",
      "ROCKET",
      "SHURI",
      "MAN-APE",
      "RED SKULL",
      "NICK FURY",
      "MARIA HILL",
    ],
  },
  {
    phase: "III",
    title: "ANT-MAN AND THE WASP",
    date: "3 AUGUST 2019",
    img: "",
    heroes: ["ANT-MAN", "WASP", "HANK PYM", "GHOST", "CASSANDRA LANG"],
  },
  {
    phase: "III",
    title: "CAPITAN MARVEL",
    date: "8 MARCH 2019",
    img: "",
    heroes: [
      "NICK FURY",
      "CAPITAN MARVEL",
      "TALOS",
      "YON-ROGG",
      "MARIA RAMBEAU",
      "RONAN",
    ],
  },
  {
    phase: "III",
    title: "AVENGERS: ENDGAME",
    date: "25 APRIL 2019",
    img: "",
    heroes: [
      "IRON MAN",
      "CAPITAN MARVEL",
      "CAPITAN AMERICA",
      "HULK",
      "THOR",
      "BLACK WIDOW",
      "HAWKEYE",
      "WAR MACHINE",
      "ANT-MAN",
      "NEBULA",
      "THANOS",
      "ROCKET",
      "DOCTOR STRANGE",
      "BLACK PANTHER",
      "SPIDER-MAN",
      "STAR-LORD",
      "GAMORA",
      "WASP",
      "VALKYRIE",
      "SCARLET WITCH",
      "FALCON",
      "LOKI",
      "OKOYE",
      "WONG",
      "MANTIS",
      "DRAX",
      "SHURI",
      "ANCIENT ONE",
      "KORG",
      "HANK PYM",
      "MARIA HILL",
      "MAN-APE",
      "VISION",
      "GROOT",
      "NICK FURY",
      "RED SKULL",
      "CASSANDRA LANG",
      "JANE FOSTER",
    ],
  },
  {
    phase: "III",
    title: "SPIDER-MAN: FAR FROM HOME",
    date: "5 JULY 2019",
    img: "",
    heroes: ["SPIDER-MAN", "MYSTERIO", "NICK FURY", "MARIA HILL", "TALOS"],
  },

  {
    phase: "IV",
    title: "WANDAVISION",
    date: "15 JANUARY 2021",
    img: "",
    heroes: [
      "SCARLET WITCH",
      "VISION",
      "DARCY LEWIS",
      "AGATA HARKNESS",
      "MONICA RAMBEAU",
      "WHITE VISION",
      "BILLY MAXIMOFF",
      "TOMMY MAXIMOFF",
    ],
  },

  {
    phase: "IV",
    title: "FALCON AND THE WINTER SOLDIER",
    date: "19 MARCH 2021",
    img: "",
    heroes: [
      "WINTER SOLDIER",
      "FALCON",
      "ZEMO",
      "OKOYE",
      "SHARON CARTER",
      "JOHN WALKER",
    ],
  },

  {
    phase: "IV",
    title: "LOKI",
    date: "9 JUNE 2021",
    img: "",
    heroes: ["LOKI", "SYLVIE", "XIALING", "KANG THE CONQUEROR"],
  },

  {
    phase: "IV",
    title: "BLACK WIDOW",
    date: "9 JULY 2021",
    img: "",
    heroes: ["BLACK WIDOW", "TASKMASTER", "YELENA", "RED GUARDIAN"],
  },

  {
    phase: "IV",
    title: "WHAT IF...?",
    date: "11 AUGUST 2021",
    img: "",
    heroes: [
      "THE WATCHER",
      "NICK FURY",
      "BLACK PANTHER",
      "IRON MAN",
      "BLACK WIDOW",
      "HAWKEYE",
      "DOCTOR STRANGE",
      "CAPITAN MARVEL",
      "OKOYE",
      "ULTRON",
      "LOKI",
      "CAPITAN MARVEL",
      "HULK",
      "KILLMONGER",
      "THOR",
      "NEBULA",
      "PHIL COULSON",
      "WINTER SOLDIER",
      "EGO",
      "STAR-LORD",
      "JANE FOSTER",
      "HANK PYM",
      "YONDU",
      "WONG",
      "DARCY LEWIS",
      "ANCIENT ONE",
      "WASP",
      "ANT-MAN",
      "THE GRAND MASTER",
      "WAR MACHINE",
      "SPIDER-MAN",
      "PEGGY CARTER",
    ],
  },

  {
    phase: "IV",
    title: "SHANG-CHI AND THE LEGEND OF THE TEN RINGS",
    date: "3 SEPTEMBER 2021",
    img: "",
    heroes: ["SHANG-CHI", "MANDARYN", "XIALING", "WONG"],
  },

  {
    phase: "IV",
    title: "ETERNALS",
    date: "5 NOVEMBER 2021",
    img: "",
    heroes: [
      "SERSI",
      "ICARIS",
      "THENA",
      "AJAK",
      "KINGO",
      "DANE WHITMAN",
      "SPRITE",
      "PHASTOS",
      "MAKKARI",
      "DRUIG",
      "GILGAMESH",
    ],
  },

  {
    phase: "IV",
    title: "HAWKEYE",
    date: "24 NOVEMBER 2021",
    img: "",
    heroes: ["HAWKEYE", "KATE BISHOP", "YELENA", "KINGPIN", "ECHO"],
  },
  {
    phase: "IV",
    title: "SPIDER-MAN: NO WAY HOME",
    date: "17 DECEMBER 2021",
    img: "",
    heroes: [
      "SPIDER-MAN",
      "GREEN GOBLIN",
      "SAND-MAN",
      "DOCTOR OCTOPUS",
      "LIZARD",
      "ELECTRO",
      "DOCTOR STRANGE",
      "WONG",
    ],
  },
  {
    phase: "IV",
    title: "MOON KNIGHT",
    date: "30 MARCH 2022",
    img: "",
    heroes: ["MOON KNIGHT", "ARTHUR HARROW", "CHONSU", "LAYLA"],
  },
  {
    phase: "IV",
    title: "DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS",
    date: "6 MAY 2022",
    img: "",
    heroes: [
      "DOCTOR STRANGE",
      "SCARLET WITCH",
      "BARON MORDO",
      "WONG",
      "DR. CHRISTINE PALMER",
      "PEGGY CARTER",
      "BLACK BOLT",
      "CAPITAN MARVEL",
      "MR. FANTASTIC",
      "PROFESOR X",
      "AMERICA CHAVEZ",
      "BILLY MAXIMOFF",
      "TOMMY MAXIMOFF",
      "CAPITAN MARVEL",
      "PROFESOR X",
    ],
  },
  {
    phase: "IV",
    title: "MS. MARVEL",
    date: "8 JUNE 2022",
    img: "",
    heroes: ["MS. MARVEL", "RED DAGGER", "KAMRAN"],
  },
  {
    phase: "IV",
    title: "THOR: LOVE AND THUNDER",
    date: "8 JULY 2022",
    img: "",
    heroes: [
      "THOR",
      "JANE FOSTER",
      "GORR THE GOD BUTCHER",
      "VALKYRIE",
      "KORG",
      "STAR-LORD",
      "DRAX",
      "NEBULA",
      "MANTIS",
      "GROOT",
      "ROCKET",
      "ZEUS",
    ],
  },
  {
    phase: "IV",
    title: "SHE-HULK: ATTORNEY AT LAW",
    date: "18 AUGUST 2022",
    img: "",
    heroes: ["SHE-HULK", "TITANIA", "DAREDEVIL", "ABOMINATION", "WONG"],
  },

  {
    phase: "IV",
    title: "WEREWOLF BY NIGHT",
    date: "7 OCTOBER 2022",
    img: "",
    heroes: ["JACK RUSSEL", "ELSA BLOODSTONE", "MAN-THING"],
  },

  {
    phase: "IV",
    title: "BLACK PANTHER: WAKANDA FOREVER",
    date: "11 NOVEMBER 2022",
    img: "",
    heroes: ["SHURI", "NAKIA", "OKOYE", "MAN-APE", "NAMOR"],
  },
  {
    type: "SPECIAL",
    title: "GUARDIANS OF THE GALAXY: THE HOLIDAY SPECIAL",
    date: "8 JUNE 2022",
    img: "",
    heroes: [
      "STAR-LORD",
      "DRAX",
      "GAMORA",
      "ROCKET",
      "NEBULA",
      "MANTIS",
      "GROOT",
    ],
  },
  {
    type: "MOVIE",
    phase: "V",
    title: "ANT-MAN AND THE WASP: QUANTUMANIA",
    date: "8 JUNE 2022",
    img: "",
    heroes: [
      "ANT-MAN",
      "WASP",
      "CASSANDRA LANG",
      "KANG THE CONQUEROR",
      "HANK PYM",
    ],
  },
];
